import '@/src/styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'PayStream',
  description: 'Generated by PLTG',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/favicon.ico' />
      </head>
      <body className={`${inter.className} dark m-0 h-screen p-0`}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
